/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/YYITjb5RqoT
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"

export function dashboard() {
  return (
    <div className="flex flex-col gap-8 p-8">
      <div className="flex flex-col gap-4">
        <h1 className="text-3xl font-bold">Email Sender</h1>
        <p className="text-gray-500 dark:text-gray-400">Send files to multiple recipients with ease.</p>
      </div>
      <div className="grid grid-cols-1 gap-6 md:grid-cols-2">
        <div className="flex flex-col gap-4 rounded-lg border border-gray-200 p-6 shadow-sm dark:border-gray-800 dark:border-gray-800">
          <div className="flex items-center justify-between">
            <h2 className="text-lg font-medium">Upload File</h2>
            <Button size="sm" variant="outline">
              <FolderIcon className="h-4 w-4" />
              Browse
            </Button>
          </div>
          <Input className="w-full" type="file" />
        </div>
        <div className="flex flex-col gap-4 rounded-lg border border-gray-200 p-6 shadow-sm dark:border-gray-800 dark:border-gray-800">
          <div className="flex items-center justify-between">
            <h2 className="text-lg font-medium">Email Recipients</h2>
            <Button size="sm" variant="outline">
              <PlusIcon className="h-4 w-4" />
              Add
            </Button>
          </div>
          <div className="grid gap-2">
            <Input placeholder="Enter email address" type="email" />
            <Input placeholder="Enter email address" type="email" />
            <Input placeholder="Enter email address" type="email" />
          </div>
        </div>
      </div>
      <div className="flex flex-col gap-4 rounded-lg border border-gray-200 p-6 shadow-sm dark:border-gray-800 dark:border-gray-800">
        <div className="flex items-center justify-between">
          <h2 className="text-lg font-medium">Status</h2>
          <Button variant="primary">
            <SendIcon className="h-4 w-4" />
            Send
          </Button>
        </div>
        <div className="grid gap-2">
          <div className="flex items-center gap-2 text-sm text-gray-500 dark:text-gray-400">
            <ClockIcon className="h-4 w-4" />
            Uploading file...
          </div>
          <div className="flex items-center gap-2 text-sm text-green-500">
            <CheckIcon className="h-4 w-4" />
            Email sent successfully
          </div>
          <div className="flex items-center gap-2 text-sm text-red-500">
            <XIcon className="h-4 w-4" />
            Failed to send email
          </div>
        </div>
      </div>
    </div>
  )
}

function CheckIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M20 6 9 17l-5-5" />
    </svg>
  )
}


function ClockIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="12" cy="12" r="10" />
      <polyline points="12 6 12 12 16 14" />
    </svg>
  )
}


function FolderIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M20 20a2 2 0 0 0 2-2V8a2 2 0 0 0-2-2h-7.9a2 2 0 0 1-1.69-.9L9.6 3.9A2 2 0 0 0 7.93 3H4a2 2 0 0 0-2 2v13a2 2 0 0 0 2 2Z" />
    </svg>
  )
}


function PlusIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M5 12h14" />
      <path d="M12 5v14" />
    </svg>
  )
}


function SendIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m22 2-7 20-4-9-9-4Z" />
      <path d="M22 2 11 13" />
    </svg>
  )
}


function XIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M18 6 6 18" />
      <path d="m6 6 12 12" />
    </svg>
  )
}
